name: Build CopilotOs GSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python

    - name: Sync AOSP source
      run: |
        repo init -u https://android.googlesource.com/platform/manifest
        repo sync

    - name: Apply patches
      run: |
        git apply path/to/google/patch.patch
        git apply path/to/microsoft/patch.patch

    - name: Configure build
      run: |
        source build/envsetup.sh
        lunch aosp_arm64-ab-userdebug

    - name: Build GSI
      run: |
        make -j$(nproc) systemimage

    - name: Upload GSI
      uses: actions/upload-artifact@v2
      with:
        name: CopilotOs-GSI
        path: out/target/product/generic_arm64-ab/system.img
        
